apiVersion: v1
data:
  policies-payload.json: '[{"policies": [{"name": "Log4Shell: CVE-2021-44228 - log4j
    Remote Code Execution vulnerability", "SORTEnforcement": true, "SORTLifecycleStage":
    "DEPLOY", "SORTName": "Log4Shell: CVE-2021-44228 - log4j Remote Code Execution
    vulnerability", "categories": ["Vulnerability Management"], "criteriaLocked":
    false, "description": "Alert on deployments with images containing the Log4Shell
    vulnerability (CVE-2021-44228). This is a flaw in the Java logging library Apache
    Log4j in versions from 2.0.0 and before as well as version 2.14.1.", "disabled":
    false, "enforcementActions": ["SCALE_TO_ZERO_ENFORCEMENT", "UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT"],
    "eventSource": "NOT_APPLICABLE", "exclusions": [], "fields": null, "isDefault":
    false, "lifecycleStages": ["DEPLOY"], "mitreAttackVectors": [], "mitreVectorsLocked":
    false, "notifiers": [], "policySections": [{"policyGroups": [{"booleanOperator":
    "OR", "fieldName": "CVE", "negate": false, "values": [{"value": "CVE-2021-44228"}]}],
    "sectionName": ""}], "policyVersion": "1.1", "rationale": "This vulnerability
    allows a remote attacker to execute code on the server if the system logs an attacker-controlled
    string value with the attacker''s JNDI LDAP server lookup.", "remediation": "Update
    the log4j libary to version 2.15.0 (which disables the feature by default), 2.16.0
    (which removes the functionality) or later. If not possible to upgrade, there
    are two possible mitigations for this flaw in versions from 2.10 to 2.14.1: Set
    the system property log4j2.formatMsgNoLookups to true, or remove the JndiLookup
    class from the classpath.", "scope": [], "severity": "CRITICAL_SEVERITY", "whitelists":
    []}, {"name": "PwnKit: CVE-2021-4034 - pwnkit Privilege Escalation", "SORTEnforcement":
    true, "SORTLifecycleStage": "BUILD,DEPLOY", "SORTName": "PwnKit: CVE-2021-4034
    - pwnkit Privilege Escalation", "categories": ["Vulnerability Management", "Privileges"],
    "criteriaLocked": false, "description": "Alert on deployments with images containing
    the polkit pkexec vulnerability (CVE-2021-4034). The polkit package is designed
    to define and handle policies that allow unprivileged processes to communicate
    with privileged processes on a Linux system. Pkexec, part of polkit, is a tool
    that allows the user to execute commands as another user according to the polkit
    policy definitions using the setuid feature. The vulnerability found in pkexec
    allows an unprivileged local attacker to escalate privileges, bypassing any authentication
    and policies due to incorrect handling of the process\u2019s argument vector.",
    "disabled": false, "enforcementActions": ["SCALE_TO_ZERO_ENFORCEMENT", "UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT"],
    "eventSource": "NOT_APPLICABLE", "exclusions": [], "fields": null, "isDefault":
    false, "lifecycleStages": ["BUILD", "DEPLOY"], "mitreAttackVectors": [{"tactic":
    "TA0004", "techniques": []}], "mitreVectorsLocked": false, "notifiers": [], "policySections":
    [{"policyGroups": [{"booleanOperator": "OR", "fieldName": "CVE", "negate": false,
    "values": [{"value": "CVE-2021-4034"}]}], "sectionName": ""}], "policyVersion":
    "1.1", "rationale": "The primary risk for customers is the possibility of an unprivileged
    user gaining administrative privileges on the affected systems. The attacker must
    have login access to the target system to carry out the attack.", "remediation":
    "https://access.redhat.com/errata/RHSA-2022:0267#packages", "scope": [], "severity":
    "CRITICAL_SEVERITY", "whitelists": []}]}]'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: policies-payload
  namespace: stackrox